# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: true
exclude: Gemfile, Gemfile.lock, Makefile, Procfile, README.md, compass.rb

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: John Doe
author_email: john@doe.com
title: Jekyll Zurb Quickstart
url: http://localhost:4000

# external css files to include - e.g. google web fonts
external_css:
- url: http://fonts.googleapis.com/css?family=Open+Sans:400,700
